import type { JuseEvent } from '@/types/event';

export const SEED_EVENTS: JuseEvent[] = [
  {
    id: 'seed-1',
    date: '2026-04-30',
    startTime: '09:00',
    endTime: '11:00',
    duration: 120,
    eventType: 'Gincana',
    location: 'MANDALA MUCHIK - MOCHE',
    animadoras: ['ALISSON', 'MILENA'],
    bailarinas: ['ERIKA', 'GERAL'],
    dj: ['GIAN FRANCO'],
    staffAdicional: ['EDWARD'],
    munecos: [],
    totalEvento: 900,
    movilidad: 50,
    adelanto: 50,
    saldo: 850,
    pagoPersonal: 0,
    ganancia: 900,
    observacion: 'FACTURA DEL PAQUETE Y LA MOVILIDAD EN EFECTIVO - RUC. 20615053253 PAQUETE 2 DE 900 ---',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-2',
    date: '2026-04-30',
    startTime: '12:00',
    endTime: '14:30',
    duration: 150,
    eventType: 'Gincana',
    location: 'FUNDO VALLEJO - MOCHE',
    animadoras: ['DANIELA', 'MILENA'],
    bailarinas: ['ERIKA', 'GERAL'],
    dj: ['GIAN FRANCO'],
    staffAdicional: ['DAVID', 'DAYIRO'],
    munecos: [],
    totalEvento: 1350,
    movilidad: 40,
    adelanto: 50,
    saldo: 1300,
    pagoPersonal: 0,
    ganancia: 1350,
    observacion: 'FACTURAR TODO - RUC. 20607040681 --- PAQUETE 3 - 1350 /// EN DOS FACTURAS --- EN DIAS DINTINTOS',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-3',
    date: '2026-04-30',
    startTime: '14:00',
    endTime: '15:00',
    duration: 60,
    eventType: 'Gincana',
    location: 'REY SOL',
    animadoras: ['ALLISON'],
    bailarinas: [],
    dj: ['EDWARD'],
    staffAdicional: ['MAURICIO'],
    munecos: [],
    totalEvento: 350,
    movilidad: 0,
    adelanto: 50,
    saldo: 300,
    pagoPersonal: 0,
    ganancia: 350,
    observacion: 'SOLO CONTRATO / SIN FACTURA',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-4',
    date: '2026-05-01',
    startTime: '10:00',
    endTime: '12:30',
    duration: 150,
    eventType: 'Gincana',
    location: 'XTRA MINERAL - VILLARAN SAN ISIDRO',
    animadoras: ['FERNANDA', 'MIRELLA'],
    bailarinas: ['ERIKA', 'NICOL'],
    dj: ['GIAN FRANCO'],
    staffAdicional: ['DAYIRO', 'DAVID'],
    munecos: [],
    totalEvento: 1350,
    movilidad: 80,
    adelanto: 1430,
    saldo: 0,
    pagoPersonal: 0,
    ganancia: 1350,
    observacion: 'SOLO CONTRATO / SIN FACTURA',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-5',
    date: '2026-05-01',
    startTime: '11:00',
    endTime: '12:00',
    duration: 60,
    eventType: 'Gincana',
    location: 'QUIRUHUAC',
    animadoras: ['ALLISON'],
    bailarinas: [],
    dj: ['EDWARD'],
    staffAdicional: ['MAURICIO'],
    munecos: [],
    totalEvento: 350,
    movilidad: 100,
    adelanto: 450,
    saldo: 0,
    pagoPersonal: 0,
    ganancia: 350,
    observacion: 'PAQUETE BASICO / FACTURAR TODO - RUC. 20481829411 --- YA ESTA PAGADO',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-6',
    date: '2026-05-01',
    startTime: '15:00',
    endTime: '16:30',
    duration: 90,
    eventType: 'Gincana',
    location: 'EMP. LINEA - AVENIDA AMERICA',
    animadoras: ['FERNANDA'],
    bailarinas: ['NICOL', 'MAURICIO'],
    dj: ['EDWARD'],
    staffAdicional: [],
    munecos: [],
    totalEvento: 550,
    movilidad: 20,
    adelanto: 50,
    saldo: 500,
    pagoPersonal: 0,
    ganancia: 550,
    observacion: 'RECIBO POR HONORARIOS / CONTRATO',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-7',
    date: '2026-05-01',
    startTime: '17:00',
    endTime: '18:30',
    duration: 90,
    eventType: 'Gincana',
    location: 'VILLA MIA - CAMPIÑA DE MOCHE',
    animadoras: ['MIRELLA'],
    bailarinas: ['ERIKA', 'GERAL'],
    dj: ['GIAN FRANCO'],
    staffAdicional: [],
    munecos: [],
    totalEvento: 580,
    movilidad: 50,
    adelanto: 50,
    saldo: 530,
    pagoPersonal: 0,
    ganancia: 580,
    observacion: '',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-8',
    date: '2026-05-02',
    startTime: '09:00',
    endTime: '11:30',
    duration: 150,
    eventType: 'Gincana',
    location: 'LOCAL LA CHACRITA',
    animadoras: ['ALLISON', 'LUZ'],
    bailarinas: ['NICOL', 'MAURICIO'],
    dj: ['GIAN FRANCO'],
    staffAdicional: ['DAYIRO', 'DAVID'],
    munecos: [],
    totalEvento: 1350,
    movilidad: 0,
    adelanto: 100,
    saldo: 1250,
    pagoPersonal: 0,
    ganancia: 1350,
    observacion: '',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-9',
    date: '2026-05-02',
    startTime: '10:30',
    endTime: '12:30',
    duration: 120,
    eventType: 'Gincana',
    location: 'CENTRO RECREACIONAL DON RUIZ',
    animadoras: ['MIRELLA', 'ANITA'],
    bailarinas: ['GERAL', 'ERIKA'],
    dj: ['EDWARD'],
    staffAdicional: ['ENAMORADA GIAN'],
    munecos: [],
    totalEvento: 900,
    movilidad: 100,
    adelanto: 50,
    saldo: 850,
    pagoPersonal: 0,
    ganancia: 900,
    observacion: 'RH POR LA TOTALIDAD',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-10',
    date: '2026-05-02',
    startTime: '13:00',
    endTime: '15:30',
    duration: 150,
    eventType: 'Gincana',
    location: 'EL MILAGRO',
    animadoras: ['ALLISON', 'LUZ'],
    bailarinas: ['NICOL', 'MAURICIO'],
    dj: ['GIAN FRANCO'],
    staffAdicional: ['DAYIRO', 'DAVID'],
    munecos: [],
    totalEvento: 1350,
    movilidad: 100,
    adelanto: 1450,
    saldo: -100,
    pagoPersonal: 0,
    ganancia: 1350,
    observacion: 'YA ESTA FACTURADO - FALTA CONTRATO',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-11',
    date: '2026-05-02',
    startTime: '17:00',
    endTime: '18:30',
    duration: 90,
    eventType: 'Gincana',
    location: 'VILLA TEO - LAREDO',
    animadoras: ['MIRELLA', 'ANITA'],
    bailarinas: [],
    dj: ['EDWARD'],
    staffAdicional: ['GERAL', 'ERIKA'],
    munecos: [],
    totalEvento: 580,
    movilidad: 0,
    adelanto: 50,
    saldo: 530,
    pagoPersonal: 0,
    ganancia: 580,
    observacion: 'ES CUMPLEAÑOS - SOLO RECIBO Y CONTRATO',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-12',
    date: '2026-05-02',
    startTime: '19:00',
    endTime: '20:45',
    duration: 105,
    eventType: 'Revelación de Género',
    location: 'MI GRANJA ROSITA - HUANCHACO',
    animadoras: ['DANIELA'],
    bailarinas: [],
    dj: ['GIAN FRANCO'],
    staffAdicional: [],
    munecos: [],
    totalEvento: 300,
    movilidad: 40,
    adelanto: 50,
    saldo: 250,
    pagoPersonal: 0,
    ganancia: 300,
    observacion: '',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-13',
    date: '2026-05-03',
    startTime: '11:00',
    endTime: '12:30',
    duration: 90,
    eventType: 'Gincana',
    location: 'CARRETERA LAREDO',
    animadoras: [],
    bailarinas: [],
    dj: ['GIAN FRANCO'],
    staffAdicional: [],
    munecos: [],
    totalEvento: 550,
    movilidad: 0,
    adelanto: 0,
    saldo: 550,
    pagoPersonal: 0,
    ganancia: 550,
    observacion: '',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'seed-14',
    date: '2026-05-03',
    startTime: '16:00',
    endTime: '17:45',
    duration: 105,
    eventType: 'Gincana',
    location: 'MOCHE',
    animadoras: ['FERNANDA', 'MIRELLA'],
    bailarinas: [],
    dj: ['EDWARD'],
    staffAdicional: [],
    munecos: [],
    totalEvento: 700,
    movilidad: 100,
    adelanto: 0,
    saldo: 700,
    pagoPersonal: 0,
    ganancia: 700,
    observacion: '',

    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
